# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pythonStudygRPC.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pythonStudygRPC.proto\x12\x0fpythonStudygRPC\",\n\x0bmessageData\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t2L\n\x04\x43hat\x12\x44\n\x04send\x12\x1c.pythonStudygRPC.messageData\x1a\x1c.pythonStudygRPC.messageData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pythonStudygRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEDATA']._serialized_start=42
  _globals['_MESSAGEDATA']._serialized_end=86
  _globals['_CHAT']._serialized_start=88
  _globals['_CHAT']._serialized_end=164
# @@protoc_insertion_point(module_scope)
